# Generated by Django 4.0.6 on 2022-09-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_send',
            field=models.DateField(blank=True, null=True),
        ),
    ]
