# Generated by Django 4.0.6 on 2022-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMessages', '0002_message_date_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ticket_number',
            field=models.IntegerField(default=1),
        ),
    ]
