# Generated by Django 4.0.6 on 2022-08-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEmployees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workid',
            field=models.IntegerField(),
        ),
    ]
