# Generated by Django 4.0.6 on 2022-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIT_Team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_member',
            name='jobtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='it_member',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='it_member',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
